module.exports = {
    voices: [
        { id: 1, language: 'Arabe (ar)', nameID: 'Zeina', gender: 'Female' },
        { id: 2, language: 'Chinois (zh-ZH)', nameID: 'Zhiyu', gender: 'Female' },
        { id: 3, language: 'Danois (da-DK)', nameID: 'Naja', gender: 'Female' },
        { id: 4, language: 'Danois (da-DK)', nameID: 'Mads', gender: 'Male' },
        { id: 5, language: 'Néerlandais (nl-NL)', nameID: 'Lotte', gender: 'Female' },
        { id: 6, language: 'Néerlandais (nl-NL)', nameID: 'Ruben', gender: 'Male' },
        { id: 7, language: 'Anglais (Australian) (en-AU)', nameID: 'Nicole', gender: 'Female' },
        // { id: 8, language: 'English (Australian) (en-AU)', nameID: 'Olivia', gender: 'Female' },
        { id: 9, language: 'Anglais (Australien) (en-AU)', nameID: 'Russell', gender: 'Male' },
        { id: 10, language: 'Anglais (Britanique) (en-GB)', nameID: 'Amy', gender: 'Female' },
        { id: 11, language: 'Anglais (Britanique) (en-GB)', nameID: 'Emma', gender: 'Female' },
        { id: 12, language: 'Anglais (Britanique) (en-GB)', nameID: 'Brian', gender: 'Male' },
        { id: 13, language: 'Anglais (Indien) (en-IN)', nameID: 'Aditi', gender: 'Female' },
        { id: 14, language: 'Anglais (Indien) (en-IN)', nameID: 'Raveena', gender: 'Male' },
        // { id: 15, language: 'English (New Zealand) (en-NZ)', nameID: 'Aria', gender: 'Female' },
        // { id: 16, language: 'English (South African) (en-ZA)', nameID: 'Ayanda', gender: 'Female' },
        { id: 17, language: 'Anglais (US) (en-US)', nameID: 'Ivy', gender: 'Female (child)' },
        { id: 18, language: 'Anglais (US) (en-US)', nameID: 'Joanna', gender: 'Female' },
        { id: 19, language: 'Anglais (US) (en-US)', nameID: 'Kendra', gender: 'Female' },
        { id: 20, language: 'Anglais (US) (en-US)', nameID: 'Kimberly', gender: 'Female' },
        { id: 21, language: 'Anglais (US) (en-US)', nameID: 'Salli', gender: 'Female' },
        { id: 22, language: 'Anglais (US) (en-US)', nameID: 'Joey', gender: 'Male' },
        { id: 23, language: 'Anglais (US) (en-US)', nameID: 'Justin', gender: 'Male (child)' },
        // { id: 24, language: 'English (US) (en-US)', nameID: 'Kevin', gender: 'Male (child)' },
        { id: 25, language: 'Anglais (US) (en-US)', nameID: 'Matthew', gender: 'Male' },
        { id: 26, language: 'Anglais (Gallois) (en-GB-WLS)', nameID: 'Geraint', gender: 'Male' },
        { id: 27, language: 'Français (fr-FR)', nameID: 'Celine', gender: 'Female' },
        { id: 28, language: 'Français (fr-FR)', nameID: 'Lea', gender: 'Female' },
        { id: 29, language: 'Français (fr-FR)', nameID: 'Mathieu', gender: 'Male' },
        { id: 30, language: 'Français (Canadian) (fr-CA)', nameID: 'Chantal', gender: 'Female' },
        // { id: 31, language: 'French (Canadian) (fr-CA)', nameID: 'Gabrielle', gender: 'Female' },
        { id: 32, language: 'Alleman (de-DE)', nameID: 'Marlene', gender: 'Female' },
        { id: 33, language: 'Alleman (de-DE)', nameID: 'Vicki', gender: 'Female' },
        { id: 34, language: 'Alleman (de-DE)', nameID: 'Hans', gender: 'Male' },
        { id: 35, language: 'Hindi (hi-IN)', nameID: 'Aditi', gender: 'Female' },
        { id: 36, language: 'Islandais (is-IS)', nameID: 'Dora', gender: 'Female' },
        { id: 37, language: 'Islandais (is-IS)', nameID: 'Karl', gender: 'Male' },
        { id: 38, language: 'Italien (it-IT)', nameID: 'Carla', gender: 'Female' },
        { id: 39, language: 'Italien (it-IT)', nameID: 'Bianca', gender: 'Female' },
        { id: 40, language: 'Italien (it-IT)', nameID: 'Giorgio', gender: 'Male' },
        { id: 41, language: 'Japonais (ja-JP)', nameID: 'Mizuki', gender: 'Female' },
        { id: 42, language: 'Japonais (ja-JP)', nameID: 'Takumi', gender: 'Male' },
        { id: 43, language: 'Koréen (ko-KR)', nameID: 'Seoyeon', gender: 'Female' },
        { id: 44, language: 'Norvégienne (no-NO)', nameID: 'Liv', gender: 'Female' },
        { id: 45, language: 'Polonais (pl-PL)', nameID: 'Ewa', gender: 'Female' },
        { id: 46, language: 'Polonais (pl-PL)', nameID: 'Maja', gender: 'Female' },
        { id: 47, language: 'Polonais (pl-PL)', nameID: 'Jacek', gender: 'Male' },
        { id: 48, language: 'Polonais (pl-PL)', nameID: 'Jan', gender: 'Male' },
        { id: 49, language: 'Portuguais (Brézilien) (pt-BR)', nameID: 'Camila', gender: 'Female' },
        { id: 50, language: 'Portuguais (Brézilien) (pt-BR)', nameID: 'Vitoria', gender: 'Female' },
        { id: 51, language: 'Portuguais (Brézilien) (pt-BR)', nameID: 'Ricardo', gender: 'Male' },
        { id: 52, language: 'Portuguais (Européen) (pt-PT)', nameID: 'Ines', gender: 'Female' },
        { id: 53, language: 'Portuguais (Européen) (pt-PT)', nameID: 'Cristiano', gender: 'Male' },
        { id: 54, language: 'Roumain (ro-RO)', nameID: 'Carmen', gender: 'Female' },
        { id: 55, language: 'Russe (ru-RU)', nameID: 'Tatyana', gender: 'Female' },
        { id: 56, language: 'Espagnole (Européen) (es-ES)', nameID: 'Conchita', gender: 'Female' },
        { id: 57, language: 'Espagnole (Européen) (es-ES)', nameID: 'Lucia', gender: 'Female' },
        { id: 58, language: 'Espagnole (Européen) (es-ES)', nameID: 'Enrique', gender: 'Male' },
        { id: 59, language: 'Espagnole (Mexicain) (es-MX)', nameID: 'Mia', gender: 'Female' },
        { id: 60, language: 'Espagnole (US) (es-US)', nameID: 'Lupe', gender: 'Female' },
        { id: 61, language: 'Espagnole (US) (es-US)', nameID: 'Penelope', gender: 'Female' },
        { id: 62, language: 'Espagnole (US) (es-US)', nameID: 'Miguel', gender: 'Male' },
        { id: 63, language: 'Suédoise (sv-SE)', nameID: 'Astrid', gender: 'Female' },
        { id: 64, language: 'Turque (tr-TR)', nameID: 'Filiz', gender: 'Female' },
        { id: 65, language: 'Gallois (cy-GB)', nameID: 'Gwyneth', gender: 'Female' }
    ]
}