const Errors = {

    //Custom errors : 1
    INTERNAL_ERROR: "INTERNAL_ERROR",
    BAD_REQUEST_MISSING_INFOS: "BAD_REQUEST_MISSING_INFOS",
    BAD_REQUEST_BAD_INFOS: "BAD_REQUEST_BAD_INFOS",

    //Rights : 3
    ROLE_UNAUTHORIZED: "ROLE_UNAUTHORIZED",

    // AWS : 4
    ERROR_POLLY: "ERROR_POLLY",
    ERROR_TRANSLATE: "ERROR_TRANSLATE",

    // SIGNED URL : 5
    ERROR_DOWNLOAD: "ERROR_DOWNLOAD",
    ERROR_UPLOAD: "ERROR_UPLOAD",

    // FileManager : 6
    ERROR_READING_FILE: "ERROR_READING_FILE",
    ERROR_WRITING_FILE: "ERROR_WRITING_FILE"
};

exports.Errors = Errors;