const Errors = {

    //Custom errors : 1
    INTERNAL_ERROR: "INTERNAL_ERROR",
    BAD_REQUEST_MISSING_INFOS: "BAD_REQUEST_MISSING_INFOS",
    BAD_REQUEST_BAD_INFOS: "BAD_REQUEST_BAD_INFOS",


    //Rights : 3
    ROLE_UNAUTHORIZED: "ROLE_UNAUTHORIZED",

    // AWS : 4
    ERROR_POLLY: "ERROR_POLLY",
    ERROR_S3_DOWNLOAD: "ERROR_S3_DOWNLOAD",
    ERROR_S3_UPLOAD: "ERROR_S3_UPLOAD",
    ERROR_TRANSLATE: "ERROR_TRANSLATE"
};

exports.Errors = Errors;